name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Discord ID
      description: How can we get in touch with you if we need more info?
      placeholder: ex. Name#0000
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: expected_result
    attributes:
      label: What was the expected behvaior?
      description: How is the program supposed to act?
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
