name: Feature request
description: Suggest an idea
title: "Feature: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: feature-desc
    attributes:
      label: Describe the feature you'd like to see
      description: A clear and concise description of the feature.
      placeholder: Add more Tits.
    validations:
      required: true
  - type: textarea
    id: add-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add more Penis.
    validations:
      required: false

